#ifndef DEFAULTVALUES_H
#define DEFAULTVALUES_H

#define DEFAULT_NODE_HEIGHT 30
#define DEFAULT_NODE_WIDTH 30

#define DEFAULT_EDGE_TYPE "directed"

#define DEFAULT_NONE "none"

#endif // DEFAULTVALUES_H
